#!/bin/bash

#module unload cmake
#module load cmake/3.5.0
current=`pwd`
cd ../../../..
version=${PWD##*/}
mkdir -p default
cd default
dest=`pwd`
cd $current
mkdir -p build
cd build
/apps/CMAKE/3.5.0/bin/cmake -DCMAKE_INSTALL_PREFIX=$dest ../../../
make
make install
cd ../../../../../..
ln -s $version default
