#!/bin/bash

script=$(readlink -f "$0")
scriptpath=$(dirname "$script")
srcpath=$scriptpath/../..
versionpath=$srcpath/../..
cd $versionpath
version=${PWD##*/}
dest=$versionpath/default
mkdir -p $dest
cd $scriptpath
log=$srcpath/log
mkdir -p build
cd build
/apps/CMAKE/3.5.0/bin/cmake -DCMAKE_INSTALL_PREFIX=$dest ../../../ $log 2>&1 
make >> $log 2>&1 
make install >> $log 2>&1
path=$versionpath/..
if [ -d $path/default ]
then
  rm $path/default
fi
ln -s $path/$version $path/default
