#!/bin/bash

script=$(readlink -f "$0")
scriptpath=$(dirname "$script")
cmakelist=$scriptpath/../../CMakeLists.txt
major=`grep set\(LPAGGREG_VERSION_MAJOR $cmakelist | sed 's/set(LPAGGREG_VERSION_MAJOR\ "//' | sed 's/")//'`
minor=`grep set\(LPAGGREG_VERSION_MINOR $cmakelist | sed 's/set(LPAGGREG_VERSION_MINOR\ "//' | sed 's/")//'`
patch=`grep set\(LPAGGREG_VERSION_PATCH $cmakelist | sed 's/set(LPAGGREG_VERSION_PATCH\ "//' | sed 's/")//'`
version=$major.$minor.$patch
echo $version
