#!/bin/bash

CMAKE=/apps/CMAKE/3.2.1/bin/cmake 

script=$(readlink -f "$0")
scriptpath=$(dirname "$script")
srcpath=$scriptpath/../..
versionpath=$srcpath/../..
cd $versionpath
version=${PWD##*/}
dest=$versionpath/default
mkdir -p $dest
cd $scriptpath
mkdir -p build
cd build
$CMAKE -DCMAKE_INSTALL_PREFIX=$dest ../../.. 
make
make install
path=$versionpath/..
if [ -d $path/default ]
then
  rm $path/default
fi
ln -s $path/$version $path/default
